FROM php:8.4-apache

RUN a2enmod rewrite \
    && sed -ri 's!Listen 80!Listen 10000!g' /etc/apache2/ports.conf \
    && sed -ri 's!<VirtualHost \*:80>!<VirtualHost *:10000>!g' /etc/apache2/sites-available/000-default.conf \
    && sed -ri 's!DirectoryIndex .*!DirectoryIndex index.php index.html!' /etc/apache2/mods-enabled/dir.conf

COPY . /var/www/html/

EXPOSE 10000